# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9190f1758b8351fa93872952a25da7b2ea058f5d843898b0dc57325cd352ed5f4ab2d54c958318db301a4498ff2a0e346e5e91a6ec7321c4d6d413f927028e1c

test:
  secret_key_base: 18f0d020a5a3fd5206994abdb0ece8a9ad63332a504dd260d8db0592c048303566b6e6a060649764bda73b90801a8a2a472970d3766e3ecb0b0928a394b206c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
